const CUSTOMER_AUTHOR_TYPES = ['user', 'end_user'];
const AGENT_WORKSPACE_NAME = /^(zd-)?agentWorkspace$/i;

/**
 * Skip messages that were not written by a customer or were generated by AI.
 * @param {Object} author - Sunshine message author; an absent author is skipped.
 * @returns {boolean} Whether this message must be ignored.
 */
export function shouldSkipMessage(author) {
  const isCustomer = CUSTOMER_AUTHOR_TYPES.includes(author?.type);
  const wasGeneratedByAi = author?.subtypes?.includes('AI') === true;

  return !isCustomer || wasGeneratedByAi;
}

/**
 * Recognize agent ownership from the existing active-switchboard integration values.
 * @param {Object|string} integration - Active switchboard integration object or identifier.
 * @returns {boolean} Whether the conversation is owned by a human integration.
 */
export function isAgentActive(integration) {
  const integrationId = typeof integration === 'string' ? integration : integration?.id;
  const integrationName = typeof integration === 'string' ? integration : integration?.name;
  const configuredAgentId = process.env.SUNSHINE_AGENT_WORKSPACE_INTEGRATION_ID;

  if (configuredAgentId && integrationId === configuredAgentId) {
    return true;
  }

  return AGENT_WORKSPACE_NAME.test(integrationName || '');
}
